# Generated by Django 3.1.1 on 2021-01-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0002_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('image', models.ImageField(blank=True, default='img/bg3.jpg', upload_to='img', verbose_name='대표이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트시간')),
                ('_type', models.PositiveSmallIntegerField(choices=[(0, '해킹'), (1, '개발'), (2, '보안'), (3, '책')], verbose_name='게시글타입')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
